### ISSUE TITLE
Asp.net core .Net 5 compatibility?

### ISSUE THREAD

**Issue by StefanOssendorf** [chkr1011/MQTTnet#1017]
### Describe your question
Hello. I am using the Mqtt server with the AspNetCore integration and trying to upgrade to .Net 5 (RC2).
Sadly I get a compile error after upgrading to the latest Mqtt + .Net5 RC2 packages.

The error is:
CS7069	Reference to type 'ConnectionsRouteBuilder' claims it is defined in 'Microsoft.AspNetCore.Http.Connections', but it could not be found.

I found out that the type `ConnectionsRouterBuilder` is removed with .Net 5 hence the error.

The actual question: Is .Net 5 compatibility in work or is it planned? And if so will it be shipped before the .Net 5 release next month?

Thanks in advance

### Which project is your question related to?
- Server (AspNetCore integration)

Edit:

The method in question is 
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapMqtt("/mqtt");
});
```

**Comment by JanEggers** [comment]
> Is .Net 5 compatibility in work or is it planned? 

nothing is planned but I will update MqttNet.AspnetCore as soon as AspnetCore is Released and most likely ifdef my way to compatibility. 

> And if so will it be shipped before the .Net 5 release next month?

no it will certainly not be shipped before .Net 5 release. maybe in december when im on vakation and have some spare time. If you need to early adopt .Net 5 feel free to create a pr.

**Comment by JanEggers** [comment]
this seems to be the the issue:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#signalr-usesignalr-and-useconnections-methods-removed

**Comment by Jossec101** [comment]
Hi @StefanOssendorf  @JanEggers 

I made it work on NET 5.0 by just changing these lines in Startup.cs:

Old startup.cs:
`
                      app.UseEndpoints(endpoints =>
                {
                    endpoints.MapMqtt("/mqtt");
                });
`

.NET5 Startup.cs:
`
   app.UseEndpoints(endpoints =>
            {
                endpoints.MapConnectionHandler<MqttConnectionHandler>("/mqtt");
            });
`
I made a quick test and it is working without any issue.

Cheers

**Comment by JanEggers** [comment]
MapMqtt should call exactly that I  guess ms just changed some types so the extension is not recogniced

**Comment by 314159265meow** [comment]
Hi, maybe this is helpful for someone. Using the solution from @Jossec101 we still had a problem with the "Sec-WebSocket-Protocol". 

`WebSocket connection to '...' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

To fix that we had to specify a SubProtocolSelector, like this:

`            
builder.MapConnectionHandler<MqttConnectionHandler>("/api-gateway",
                httpConnectionDispatcherOptions => httpConnectionDispatcherOptions.WebSockets.SubProtocolSelector = protocolList => protocolList.FirstOrDefault() ?? string.Empty);
`

**Comment by chkr1011** [comment]
@SeppPenner Should we add the above hint to the wiki and close this issue?

**Comment by SeppPenner** [comment]
Good idea, if you ask me :)

**Comment by SeppPenner** [comment]
Is it correct like this: https://github.com/chkr1011/MQTTnet/wiki/Server#net-50? If yes, we can close the issue :)

**Comment by SeppPenner** [comment]
If somethings wrong just tell me and I will update the information :)

**Comment by sean-mcl** [comment]
> If somethings wrong just tell me and I will update the information :)

The code snippet has a syntax error.

**Comment by SeppPenner** [comment]
@sean-mcl I have changed the example and it should work now.

**Comment by Fungusware** [comment]
I'm still encountering this issue.

Error :   No service for type 'Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher' has been registered

Here some snippets of how I setup the MQTT Server

**ConfigureServices**
```
            services.AddSingleton<MQTT.IGMQTTServer>();
            services.AddHostedMqttServerWithServices(options => {
                var s = options.ServiceProvider.GetRequiredService<MQTT.IGMQTTServer>();
                s.ConfigureMqttServerOptions(options);
            });
            services.AddMqttConnectionHandler();
```

**Configure**

```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapRazorPages();
                endpoints.MapConnectionHandler<MqttConnectionHandler>("/mqtt", httpConnectionDispatcherOptions => httpConnectionDispatcherOptions.WebSockets.SubProtocolSelector = protocolList => protocolList.FirstOrDefault() ?? string.Empty);
            });

            app.UseMqttServer(server => app.ApplicationServices.GetRequiredService<MQTT.IGMQTTServer>().ConfigureMqttServer(server));
```


**MQTT.IGMQTTServer**

```
    internal class IGMQTTServer : MqttServer, IMqttServerClientConnectedHandler, IMqttServerClientDisconnectedHandler, IMqttServerStoppedHandler
    {
        private IMqttServer _mqttServer;
        private readonly ILogger<IGMQTTServer> _logger;

        public IGMQTTServer(IEnumerable<IMqttServerAdapter> adapters, ILogger<IGMQTTServer> logger, IMqttNetLogger mqttLogger) : base(adapters, mqttLogger)
        {
            _logger = logger;
        }

        public void ConfigureMqttServerOptions(AspNetMqttServerOptionsBuilder options)
        {
            options.WithDefaultEndpointPort(1883);
        }

        public void ConfigureMqttServer(IMqttServer mqttServer)
        {
            _logger.LogInformation($"Configuring MQTT Server. Current State : {(mqttServer.IsStarted ? "Started" : "Stopped")}");

            _mqttServer = mqttServer;
            _mqttServer.ClientConnectedHandler = this;
            _mqttServer.ClientDisconnectedHandler = this;
            _mqttServer.StoppedHandler = this;
        }

        public Task HandleClientConnectedAsync(MqttServerClientConnectedEventArgs eventArgs)
        {
            _logger.LogInformation($"Client Connected");

            return Task.CompletedTask;
        }

        public Task HandleClientDisconnectedAsync(MqttServerClientDisconnectedEventArgs eventArgs)
        {
            _logger.LogInformation($"Client Disconnected");

            return Task.CompletedTask;
        }

        public Task HandleServerStoppedAsync(EventArgs eventArgs)
        {
            _logger.LogInformation($"MQTT Server Stopped");

            return Task.CompletedTask;
        }

    }
```


Any help would be greatly appreciated, Thanks in advance.

**Comment by Fungusware** [comment]
I would like to point out that using 

`            app.UseMqttEndpoint();`

Is actually working !

**Comment by redradist** [comment]
@Fungusware Could you share your example ? Currently I tried to use MQTTnet with ASP.NET 5 without WebSockets and with Controllers and Tls support, but cannot figured out how to run it ...
Do not see connection from mqtt client:
```csharp
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMqttControllers();
            
            var currentPath = Directory.GetCurrentDirectory();
            var certificatePath = ...;

            Debug.WriteLine($"certificatePath = {certificatePath}");
            var certificate = new X509Certificate2(certificatePath, "<password>", X509KeyStorageFlags.Exportable);
            
            services
                .AddHostedMqttServer(mqttServer => mqttServer.WithoutDefaultEndpoint())
                .AddHostedMqttServerWithServices(s =>
                {
                    // Optionally set server options here
                    s.WithoutDefaultEndpoint();
                    s.WithEncryptedEndpoint();
                    s.WithEncryptedEndpointBoundIPAddress(IPAddress.Parse(Configuration["IpAddress"]));
                    s.WithEncryptedEndpointPort(int.Parse(Configuration["Port"]));
                    s.WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx));
                    s.WithEncryptionSslProtocol(SslProtocols.Tls12);
                    // Enable Attribute routing
                    s.WithAttributeRouting();
                    s.WithConnectionValidator(c =>
                    {
                        Debug.WriteLine("WithConnectionValidator");
                        c.ReasonCode = MqttConnectReasonCode.Success;
                    });
                })
                // Identify and build routes for the current assembly
                .AddMqttConnectionHandler()
                .AddConnections();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                //app.UseWebAssemblyDebugging();
                app.UseHsts();
            }
            
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                // Root endpoint for MQTT - attribute routing picks up after this URL
                endpoints.MapConnectionHandler<MqttConnectionHandler>("/mqtt");
            });
        }
    }
```
I want to use MVC controllers, but it is hard to figured out how to run properly MQTT Server

**Comment by GPT-John** [comment]
Unfortunately I no longer have this working as I did not need the MQTT functionality. Sorry.
