### ISSUE TITLE
Connecting to AWS-IoT

### ISSUE THREAD

**Issue by rowandempster** [chkr1011/MQTTnet#109]
Hello,

I am trying to use your MQTT client to connect to AWS-IoT using a presigned websocket url as outlined here: http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html.

Here is my connection code (`creds.presignedUrl` contains the authentication headers needed as a query string): 
```
            string CLIENT_ID = "notifications-test-mqtt-" + (new Random()).Next(1, 100000);
            var client = new MqttFactory().CreateMqttClient();
            var options = new MqttClientOptionsBuilder()
                .WithWebSocketServer(creds.presignedUrl)
                .WithClientId(CLIENT_ID)
                .Build();
            MqttClientConnectResult res = await client.ConnectAsync(options);
```
The issue is that `client.ConnectAsync(options)` never completes, it fails with a `MQTTnet.Core.Exceptions.MqttCommunicationTimedOutException` after about 10 seconds. 

Any suggestions? Is what I am trying to do possible?

Thank you,
Rowan

**Comment by rowandempster** [comment]
Here are the trace logs:
```
>> [2017-11-14T16:17:42.7035500-05:00] [10] [MQTTnet.Core.Client.MqttClient] [Error]: Error while connecting with server.
MQTTnet.Core.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Core.Exceptions.MqttCommunicationTimedOutException' was thrown.
  at MQTTnet.Core.Internal.TaskExtensions+<TimeoutAfter>d__0.MoveNext () [0x000c0] in <bc11562943ca45afae7b876612b36c9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter+<ConnectAsync>d__7.MoveNext () [0x0008e] in <bc11562943ca45afae7b876612b36c9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at MQTTnet.Core.Client.MqttClient+<ConnectAsync>d__24.MoveNext () [0x0015b] in <bc11562943ca45afae7b876612b36c9e>:0 
>> [2017-11-14T16:17:42.7147780-05:00] [10] [MQTTnet.Core.Client.MqttClient] [Warning]: Error while disconnecting from adapter.
MQTTnet.Core.Exceptions.MqttCommunicationException: Object reference not set to an instance of an object ---> System.NullReferenceException: Object reference not set to an instance of an object
  at System.Net.WebSockets.WebSocketHandle.CloseAsync (System.Net.WebSockets.WebSocketCloseStatus closeStatus, System.String statusDescription, System.Threading.CancellationToken cancellationToken) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/external/corefx/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs:69 
  at System.Net.WebSockets.ClientWebSocket.CloseAsync (System.Net.WebSockets.WebSocketCloseStatus closeStatus, System.String statusDescription, System.Threading.CancellationToken cancellationToken) [0x00006] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/external/corefx/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs:179 
  at MQTTnet.Implementations.MqttWebSocketChannel+<DisconnectAsync>d__12.MoveNext () [0x00059] in <aa41199fd3b34235af33df430d7236ac>:0 
   --- End of inner exception stack trace ---
  at MQTTnet.Core.Internal.TaskExtensions+<TimeoutAfter>d__0.MoveNext () [0x000f6] in <bc11562943ca45afae7b876612b36c9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter+<DisconnectAsync>d__8.MoveNext () [0x00091] in <bc11562943ca45afae7b876612b36c9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/3.8.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at MQTTnet.Core.Client.MqttClient+<DisconnectInternalAsync>d__33.MoveNext () [0x000c1] in <bc11562943ca45afae7b876612b36c9e>:0 
```

**Comment by chkr1011** [comment]
Hi,
thanks for sharing your issue. Can you provide the values for the parameters (even randomized for security reasons)? I read the document and saw that the WebSocket connection must be encrypted. This requires a wss:// in front of the URI but the library only adds ws:// if the prefix is not there.

Best regards
Christian

**Comment by rowandempster** [comment]
By parameters I assume you mean the query string parameters. Here is an example of a `presignedUrl` that I am using: 
```
ws://<iot-endpoint-id>.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<credentials>%2Fus-east-1%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20171115T190232Z&X-Amz-SignedHeaders=host&X-Amz-Signature=<sig-hash>&X-Amz-Security-Token=<aws-secturity-token>
```
When I use `wss://` as a prefix instead of `ws://` I get a `MQTTnet.Core.Exceptions.MqttCommunicationException` with error message `Unable to connect to the remote server`.

Thanks for you help,
Rowan

**Comment by chkr1011** [comment]
Thank you. I will have a look. We also have a bug in WebSocket handling probably it is related and will be fixed in the next version.

**Comment by chkr1011** [comment]
I just released a preview of 2.5.2 (available as nuget). Please test with this version again. It fixed several issues with WebSocket clients. If it does not work please let me know. We can investigate the issue then again.

**Comment by chkr1011** [comment]
@rowandempster Version 2.5.3 is already released. If the issue still exists please reopen this ticket or create a new one.

**Comment by gawde-abhijeet** [comment]
I tried the similar code example @rowandempster  posted but no luck. 
Getting error message: "Unable to connect to the remote server"

I'm using the latest version MQTTnet 2.6.0

**Comment by liuhongbo2016** [comment]
I tried v2.6.0 with the aws presigned websocket url, it does not work.

**Comment by liuhongbo** [comment]
here is how i made it work:

(options.ChannelOptions as MqttClientWebSocketOptions).SubProtocols = new List<string>();
(options.ChannelOptions as MqttClientWebSocketOptions).SubProtocols.Add("mqtt");

Since this is a mqtt library, i would say it would be better to set this subprotocols in the library itself?

**Comment by davidtruchon** [comment]
I am getting a forbidden error using a presigned url with the wss:// prefix

**Comment by brnkrygs** [comment]
I've also had luck with the approach @liuhongbo took.

I'm guessing it has to do with the fact that the AWS IoT service has connection urls that look like this:
`wss://{id}.iot.{region}.amazonaws.com/mqtt?......` as opposed to other brokers that don't have the trailing `mqtt` on the URL

**Comment by davidtruchon** [comment]
Here is my sample project if anyone wish to take a look. 

https://pastebin.com/xgdyH9CD

**Comment by davidtruchon** [comment]
I fixed it, the issue was with my code. I was using a wrong body hash to compute my signature. It worked somehow to fetch files from s3 but not with iot.

**Comment by acrabb** [comment]
Hm, i've got the same URL from both JS and the mobile client, and have all the comments here. But its still not connecting.
Was there any special settings in AWS need to make this work?
