### ISSUE TITLE
Exception & Crash on disconnect

### ISSUE THREAD

**Issue by acrabb** [chkr1011/MQTTnet#198]
In both iOS and Android now, we're getting a crash when calling `Client.DisconnectAsync`

has anyone else seen this?

```
[mono] Unhandled Exception:
[mono] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
[mono] Object name: 'MobileAuthenticatedStream'.
[mono]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[mono]   at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001bf] in <bcdc1df2b3724ab69797f3819a126346>:0 
[mono]    --- End of inner exception stack trace ---
```

**Comment by chkr1011** [comment]
Hi @acrabb ,
thanks for reporting this issue. I already fixed this for the next version (2.7.2).
Best regards
Christian

**Comment by acrabb** [comment]
Thanks @chkr1011 ! Any estimate on a release date?

**Comment by chkr1011** [comment]
A preview maybe this weekend.

**Comment by chkr1011** [comment]
Version 2.7.2 is now released. Please let me know if the issue is fixed now.

**Comment by acrabb** [comment]
Hey @chkr1011 , looks like the exception is still being thrown in 2.7.2
```
2018-03-30 11:58:22.748 Wolf.iOS[47377:88836815] 
Unhandled Exception:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001b9] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:380 
   --- End of inner exception stack trace ---
  at Wolf.iOS.AppDelegate.HandleUnobservedTaskException (System.Object sender, System.Threading.Tasks.UnobservedTaskExceptionEventArgs args) [0x00034] in /Users/andre.crabb/git/wolf/Wolf.iOS/AppDelegate.cs:193 
  at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException (System.Object sender, System.Threading.Tasks.UnobservedTaskExceptionEventArgs ueea) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskScheduler.cs:529 
  at System.Threading.Tasks.TaskExceptionHolder.Finalize () [0x000e6] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskExceptionHolder.cs:142 
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001b9] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:380 <---

2018-03-30 11:58:22.748 Wolf.iOS[47377:88836815] Unhandled managed exception:
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (System.AggregateException)
  at Wolf.iOS.AppDelegate.HandleUnobservedTaskException (System.Object sender, System.Threading.Tasks.UnobservedTaskExceptionEventArgs args) [0x00034] in /Users/andre.crabb/git/wolf/Wolf.iOS/AppDelegate.cs:193 
  at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException (System.Object sender, System.Threading.Tasks.UnobservedTaskExceptionEventArgs ueea) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskScheduler.cs:529 
  at System.Threading.Tasks.TaskExceptionHolder.Finalize () [0x000e6] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskExceptionHolder.cs:142 
 --- inner exception ---
Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'. (System.ObjectDisposedException)
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001b9] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:380 
2018-03-30 11:58:22.748 Wolf.iOS[47377:88836815] critical: Stacktrace:

2018-03-30 11:58:22.748 Wolf.iOS[47377:88836815] critical: 
Native stacktrace:

2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	0   Wolf.iOS                            0x000000010eca0a44 mono_handle_native_crash + 244
2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	1   libsystem_platform.dylib            0x000000011d794b3a _sigtramp + 26
2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	2   ???                                 0x000000000000ffff 0x0 + 65535
2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	3   libsystem_c.dylib                   0x000000011d42e0eb abort + 127
2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	4   Wolf.iOS                            0x000000010ee5b9cf xamarin_unhandled_exception_handler + 47
2018-03-30 11:58:22.760 Wolf.iOS[47377:88836815] critical: 	5   Wolf.iOS                            0x000000010ed0da54 mono_invoke_unhandled_exception_hook + 148
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	6   Wolf.iOS                            0x000000010edbcfde mono_thread_internal_unhandled_exception + 110
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	7   Wolf.iOS                            0x000000010ed0f36a mono_gc_run_finalize + 842
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	8   Wolf.iOS                            0x000000010edf93fc sgen_gc_invoke_finalizers + 236
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	9   Wolf.iOS                            0x000000010ed10b74 finalizer_thread + 324
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	10  Wolf.iOS                            0x000000010edbdaa0 start_wrapper + 704
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	11  libsystem_pthread.dylib             0x000000011d7a693b _pthread_body + 180
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	12  libsystem_pthread.dylib             0x000000011d7a6887 _pthread_body + 0
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 	13  libsystem_pthread.dylib             0x000000011d7a608d thread_start + 13
2018-03-30 11:58:22.761 Wolf.iOS[47377:88836815] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by chkr1011** [comment]
Hi,
please try again with version 2.7.3-rc3. I fixed several disconnect issues.
Best regards
Christian

**Comment by acrabb** [comment]
works great :)

**Comment by acrabb** [comment]
hm, looks like this is still happening for iOS. I've upgraded to 2.7.4
Not sure if @Flo1987 (https://github.com/chkr1011/MQTTnet/issues/210) is seeing it too?

```
2018-04-27 10:51:40.775 Wolf.iOS[4764:86068] (Workout) IMqttPipe: disconnected
2018-04-27 10:51:40.792 Wolf.iOS[4764:83576] (Error) UnobservedTaskException: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001b9] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:380 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x001b9] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:380 <---
```
